-   id: go-check-version
    name: 'go check version'
    entry: check-go-version.sh
    files: '\.go$'
    language: 'script'
    description: "Validate golang version supported, requires go.mod file in module"
